// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://amuocztzahdslafeeauo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFtdW9jenR6YWhkc2xhZmVlYXVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwNDYyMTgsImV4cCI6MjA3MTYyMjIxOH0.C1cvH97s77SFwzMZHusUofaJ5i8_MllGBfL5BurVX5Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});